<a href="https://colab.research.google.com/github/DeniseYuki/TCC/blob/main/Contagens_de_casos_e_mortes_relatadas_mais_recentes_e_classifica%C3%A7%C3%A3o_de_transmiss%C3%A3o_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Contagens de casos e mortes relatadas mais recentes e classificação de transmissão**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mp
import csv
from matplotlib import pyplot as plt

In [ ]:
arquivo = pd.read_csv('WHO-COVID-19-global-table-data.csv')

arquivo.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
0,Global,NaN,128540982,1646.629087,3988847,51.097723,650765,2808308,35.974843,68161,0.873153,11608,NaN
1,United States of America,Americas,30095776,9092.310000,442172,133.590000,65692,545887,164.920000,6860,2.070000,865,Community transmission
2,Brazil,Americas,12658109,5955.090000,528090,248.440000,84494,317646,149.440000,18970,8.920000,3780,Community transmission
3,India,South-East Asia,12221665,885.630000,434131,31.460000,72330,162927,11.810000,2235,0.160000,459,Clusters of cases
4,France,Europe,4569568,7000.650000,263463,403.630000,58828,95062,145.640000,2454,3.760000,299,Community transmission

In [ ]:
df = pd.read_csv("WHO-COVID-19-global-table-data.csv")

In [ ]:
df.columns.values

array(['Name', 'WHO Region', 'Cases - cumulative total',
       'Cases - cumulative total per 100000 population',
       'Cases - newly reported in last 7 days',
       'Cases - newly reported in last 7 days per 100000 population',
       'Cases - newly reported in last 24 hours',
       'Deaths - cumulative total',
       'Deaths - cumulative total per 100000 population',
       'Deaths - newly reported in last 7 days',
       'Deaths - newly reported in last 7 days per 100000 population',
       'Deaths - newly reported in last 24 hours',
       'Transmission Classification'], dtype=object)

In [ ]:
df.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
0,Global,NaN,128540982,1646.629087,3988847,51.097723,650765,2808308,35.974843,68161,0.873153,11608,NaN
1,United States of America,Americas,30095776,9092.310000,442172,133.590000,65692,545887,164.920000,6860,2.070000,865,Community transmission
2,Brazil,Americas,12658109,5955.090000,528090,248.440000,84494,317646,149.440000,18970,8.920000,3780,Community transmission
3,India,South-East Asia,12221665,885.630000,434131,31.460000,72330,162927,11.810000,2235,0.160000,459,Clusters of cases
4,France,Europe,4569568,7000.650000,263463,403.630000,58828,95062,145.640000,2454,3.760000,299,Community transmission

**Os 10 primeiros paises que tiveram o maior número de casos**

In [ ]:
df.head(n=11)

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
0,Global,NaN,128540982,1646.629087,3988847,51.097723,650765,2808308,35.974843,68161,0.873153,11608,NaN
1,United States of America,Americas,30095776,9092.310000,442172,133.590000,65692,545887,164.920000,6860,2.070000,865,Community transmission
2,Brazil,Americas,12658109,5955.090000,528090,248.440000,84494,317646,149.440000,18970,8.920000,3780,Community transmission
3,India,South-East Asia,12221665,885.630000,434131,31.460000,72330,162927,11.810000,2235,0.160000,459,Clusters of cases
4,France,Europe,4569568,7000.650000,263463,403.630000,58828,95062,145.640000,2454,3.760000,299,Community transmission
5,Russian Federation,Europe,4554264,3120.760000,61572,42.190000,9169,99233,68.000000,2621,1.800000,383,Clusters of cases
6,The United Kingdom,Europe,4345792,6401.600000,32880,48.430000,4052,126713,186.660000,331,0.490000,43,Community transmission
7,Italy,Europe,3584899,5929.190000,144037,238.230000,23887,109346,180.850000,3007,4.970000,467,Clusters of cases
8,Turkey,Europe,3317182,3933.150000,225900,267.850000,39302,31537,37.390000,1075,1.270000,152,Community transmission
9,Spain,Europe,3274150,7002.810000,28056,60.010000,0,75215,160.870000,129,0.280000,0,Community transmission
10,Germany,Europe,2833173,3381.520000,119993,143.220000,24300,76543,91.360000,1103,1.320000,201,Community transmission

**Os Paises que tiveram pouco ou nenhum caso**

In [ ]:
df.tail(20)

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
217,Montserrat,Americas,20,400.08,0,0.00,0,1,20.0,0,0.0,0,Sporadic cases
218,Sint Eustatius,Americas,20,637.15,0,0.00,0,0,0.0,0,0.0,0,No cases
219,Solomon Islands,Western Pacific,19,2.77,1,0.15,0,0,0.0,0,0.0,0,No cases
220,Saba,Americas,6,310.40,0,0.00,0,0,0.0,0,0.0,0,No cases
221,Marshall Islands,Western Pacific,4,6.76,0,0.00,0,0,0.0,0,0.0,0,No cases
222,Samoa,Western Pacific,4,2.02,0,0.00,0,0,0.0,0,0.0,0,No cases
223,Vanuatu,Western Pacific,3,0.98,0,0.00,0,0,0.0,0,0.0,0,No cases
224,American Samoa,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
225,Cook Islands,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
226,Democratic People's Republic of Korea,South-East Asia,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
227,Kiribati,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
228,Micronesia (Federated States of),Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
229,Nauru,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
230,Niue,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
231,Palau,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
232,Pitcairn Islands,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
233,Tokelau,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
234,Tonga,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
235,Turkmenistan,Europe,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases
236,Tuvalu,Western Pacific,0,0.00,0,0.00,0,0,0.0,0,0.0,0,No cases

**Quantidade de paises  região**

In [ ]:
df["WHO Region"].value_counts()

Europe                   62
Americas                 56
Africa                   49
Western Pacific          35
Eastern Mediterranean    22
South-East Asia          11
Other                     1
Name: WHO Region, dtype: int64

In [ ]:
df["Transmission Classification"].value_counts()

Community transmission    145
Clusters of cases          44
No cases                   23
Sporadic cases             20
Pending                     3
Not applicable              1
Name: Transmission Classification, dtype: int64

In [ ]:
arquivo

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
0,Global,NaN,128540982,1646.629087,3988847,51.097723,650765,2808308,35.974843,68161,0.873153,11608,NaN
1,United States of America,Americas,30095776,9092.310000,442172,133.590000,65692,545887,164.920000,6860,2.070000,865,Community transmission
2,Brazil,Americas,12658109,5955.090000,528090,248.440000,84494,317646,149.440000,18970,8.920000,3780,Community transmission
3,India,South-East Asia,12221665,885.630000,434131,31.460000,72330,162927,11.810000,2235,0.160000,459,Clusters of cases
4,France,Europe,4569568,7000.650000,263463,403.630000,58828,95062,145.640000,2454,3.760000,299,Community transmission
...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Pitcairn Islands,Western Pacific,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,No cases
233,Tokelau,Western Pacific,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,No cases
234,Tonga,Western Pacific,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,No cases
235,Turkmenistan,Europe,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,No cases
236,Tuvalu,Western Pacific,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,No cases

In [ ]:
arquivo.columns

Index(['Name', 'WHO Region', 'Cases - cumulative total',
       'Cases - cumulative total per 100000 population',
       'Cases - newly reported in last 7 days',
       'Cases - newly reported in last 7 days per 100000 population',
       'Cases - newly reported in last 24 hours', 'Deaths - cumulative total',
       'Deaths - cumulative total per 100000 population',
       'Deaths - newly reported in last 7 days',
       'Deaths - newly reported in last 7 days per 100000 population',
       'Deaths - newly reported in last 24 hours',
       'Transmission Classification'],
      dtype='object')

In [ ]:
arquivo.describe()

,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
count,2.370000e+02,236.000000,2.370000e+02,236.000000,237.000000,2.370000e+02,236.000000,237.000000,236.000000,237.000000
mean,1.084734e+06,2652.774911,3.366116e+04,101.549270,5491.687764,2.369880e+04,43.660741,575.198312,1.261412,97.957806
std,8.639360e+06,3197.880123,2.649364e+05,170.748104,43276.216233,1.876292e+05,59.413513,4622.691763,2.554368,796.598669
min,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,2.842000e+03,144.832500,3.600000e+01,1.385000,0.000000,2.900000e+01,1.487500,0.000000,0.000000,0.000000
50%,2.886300e+04,1334.550000,6.900000e+02,21.485000,44.000000,4.240000e+02,14.820000,10.000000,0.170000,1.000000
75%,2.358540e+05,4681.222500,6.764000e+03,119.252500,1072.000000,3.785000e+03,69.145000,83.000000,1.292500,11.000000
max,1.285410e+08,15543.910000,3.988847e+06,1066.220000,650765.000000,2.808308e+06,279.010000,68161.000000,18.330000,11608.000000

In [ ]:
arquivo.dtypes

Name                                                             object
WHO Region                                                       object
Cases - cumulative total                                          int64
Cases - cumulative total per 100000 population                  float64
Cases - newly reported in last 7 days                             int64
Cases - newly reported in last 7 days per 100000 population     float64
Cases - newly reported in last 24 hours                           int64
Deaths - cumulative total                                         int64
Deaths - cumulative total per 100000 population                 float64
Deaths - newly reported in last 7 days                            int64
Deaths - newly reported in last 7 days per 100000 population    float64
Deaths - newly reported in last 24 hours                          int64
Transmission Classification                                      object
dtype: object